import Head from "next/head";
import Header from "@/components/Header/Header";
import Hero from "@/components/Hero/Hero";
import Structure from "@/components/Structure/Structure";
import Benefits from "@/components/Benefits/Benefits";
import Advantages from "@/components/Advantages/Advantages";
import Steps from "@/components/Steps/Steps";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main>
        <div className={"mb-16 md:mb-32 xl:mb-56"}>
          <Hero />
        </div>
        <div className={"mb-36 md:mb-48 xl:mb-72"}>
          <Structure />
        </div>
        <div className={"mb-36 md:mb-48 xl:mb-72"}>
          <Benefits />
        </div>

        <div className={"mb-32 xl:mb-52"}>
          <Advantages />
        </div>

        <Steps />
      </main>
    </>
  );
}
